### ISSUE TITLE
Works great. Any thought on adding the "Live Only" option?

### ISSUE THREAD

**Issue by Dirwinc** [MarkGaretz/ATOM-Matrix-Tally-Light#11]
Thanks for putting this code together.  Works great.  Have you considered adding a "Live Only" option?  Guido implemented it recently for the M5StickC.  I use it all the time on the M5StickC because it simplifies my weekly explanation to my volunteer stage talent.

Also, FYI, In order for me to get the code to compile with Arduino IDE, I had to remove the following lines of code from glcdfont.c:
```
<<<<<<< HEAD
=======
>>>>>>> a42707567558830c1c85a28b5d31c217e9304290
```
Thanks,
Dirwin

**Comment by MarkGaretz** [comment]
Thanks.  I have tried to integrate my code with Guido's latest, but something in the new code is not working.  I haven't circled back to it to debug it as I really don't need any of the new features.  But doing a Live only mode is a simple mod to the code:

In the vMix code file, under the setTallyPreview section, change:

matrix.fillScreen(matrix.Color(0,255,0));

to

matrix.fillScreen(matrix.Color(0,0,0));

**Comment by Dirwinc** [comment]
Ok, thanks, I'll try that out.
