### ISSUE TITLE
Feature request to use this for an on-air light via an http get command.

### ISSUE THREAD

**Issue by fgolman** [MarkGaretz/ATOM-Matrix-Tally-Light#5]
Would be very cool if you have a mini API that I could send an http get command to, to turn on and off from any app. Particularly thinking about using it for a mini on-air light to be toggled from a dedicated control surface button that can be set up to send those commands.

**Comment by fgolman** [comment]
Basically, this:

https://github.com/KodeMunkie/atomictext

I just can't figure out how to compile it and push to the Atom. It's not in Arduino, just pure C++ ... which I am not familiar enough to make work. Maybe you can look at his code and implement it in Arduino.

**Comment by MarkGaretz** [comment]
Not me either, sorry.  But you should look at the scrolling text for the atom as referenced in my readme, which is where the 5x5 font is from.  I think it will do what you want.

**Comment by fgolman** [comment]
I got Atomic Text to work and it's pretty nice. It uses mDNS which is kind of interesting, never been exposed to that before but it works!
